[package]
name = "@myco/typescript"
version = "5.0.4"
description = "Typescript wrapper for Myco"
pre_pack = "default"

[registries]
registry = "file:///home/nathan/dev/myco_registry/index.toml"

[run]
default = "build"

